In [14]:
import numpy as np
from math import factorial
size = int(input("Enter a board size: "))
board = np.zeros((size,size))
for i in np.arange(size):
    for j in np.arange(size):
        if i < j:
            board[i,j] = 0
        elif i == j:
            board[i,j] = 1
        else:
            board[i,j] = factorial(i)/(factorial(i-j)*factorial(j))
print(board)    

Enter a board size: 7
[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  0.  0.  0.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.  0.]
 [ 1.  3.  3.  1.  0.  0.  0.]
 [ 1.  4.  6.  4.  1.  0.  0.]
 [ 1.  5. 10. 10.  5.  1.  0.]
 [ 1.  6. 15. 20. 15.  6.  1.]]
